homeassistant:
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor manual: !include_dir_merge_list sensors/
person: !include persons.yaml
notify: !include notify.yaml
input_boolean: !include inputs.yaml

default_config:

mobile_app:

my:

frontend:
  themes: !include themes.yaml

config:

lovelace:

api:

system_health:

auth:

conversation:

sun:

device_sun_light_trigger:
  light_group: light.couch_lights
  device_group: group.people

history:

recorder:
  db_url: !secret sql_db_url
  exclude:
    entities:
      - sensor.time
      - sensor.internet_time
      - sensor.owm_wind_speed # m/s
      - sensor.owm_pressure # mbar
      - sensor.date_time_iso
      - sensor.dishbert_remaining_program_time
    entity_globs:
      - sensor.litfassstrasse*
      - sensor.zippererstrasse*

logbook:

tts:
  - platform: google_translate
    service_name: google_say

shopping_list:

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret chat_id_0

google_assistant:
  project_id: grubfx-home-assistant
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true

wake_on_lan:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - !secret router_ip
    - !secret nas_ip
    - !secret npm_ip
  cors_allowed_origins:
    - https://cast.home-assistant.io
websocket_api:

energy:

powercalc:

plant: !include plants.yaml
