homeassistant:
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor manual: !include_dir_merge_list sensors/
person: !include persons.yaml
light: !include lights.yaml
notify: !include notify.yaml
input_boolean: !include inputs.yaml

mobile_app:

my:

frontend:
  themes: !include themes.yaml

config:

lovelace:

api:

system_health:

auth:

discovery:

conversation:

sun:
  elevation: 350

device_sun_light_trigger:
  light_group: light.couch_lights
  device_group: group.people

history:

recorder:
  db_url: !secret sql_db_url
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    entities:
      - sensor.time
      - sensor.internet_time
      - sensor.dark_sky_wind_gust # m/s
      - sensor.dark_sky_wind_speed # m/s
      - sensor.owm_wind_speed # m/s
      - sensor.dark_sky_pressure # mbar
      - sensor.owm_pressure # mbar
      - sensor.date_time_iso
      - sensor.dishbert_remaining_program_time

logbook:

map:

tts:
  - platform: google_translate
    service_name: google_say

binary_sensor:
  - platform: workday
    country: AT
    province: 8
  - platform: uptimerobot
    api_key: !secret uptimerobot_api_key
  - platform: apcupsd

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
  - platform: zamg

apcupsd:

shopping_list:

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret chat_id_0

pi_hole:
  host: !secret pihole_host
  api_key: !secret pihole_api_key

proximity:
  home:
    devices:
      - !secret tracker_0
    tolerance: 50
  cf:
    devices:
      - !secret tracker_0
    tolerance: 50

google_assistant:
  project_id: grubfx-home-assistant
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true

hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: true

media_player:
  - platform: androidtv
    host: !secret kagis_tv_ip
    apps:
      tv.arte.plus7: "Arte"
      com.nousguide.android.orftvthek: "ORF TVthek"
      com.amazon.amazonvideo.livingroom: "Amazon Prime Video"
      com.nousguide.android.rbtv: "Red Bull TV"
      com.zdf.android.mediathek: "ZDFmediathek"
      com.zappntv: "ZAPPN TV"
      com.codingbuffalo.aerialdream: "Screensaver"
      de.prosiebensat1digital.sat1: "ProSieben / SAT.1"
    state_detection_rules:
      "com.netflix.ninja":
        - "media_session_state"
      "com.plexapp.android":
        - "paused":
            "media_session_state": 3 # this indentation is important!
            "wake_lock_size": 1 # this indentation is important!
        - "playing":
            "media_session_state": 3 # this indentation is important!
        - "standby"

wake_on_lan:

mqtt:
  discovery: true
  discovery_prefix: zwave2mqtt
  broker: !secret mqtt_broker
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"
  sensor:
    - state_topic: zigbee2mqtt/bridge/networkmap/raw
      name: Zigbee2mqtt Networkmap
      value_template: >-
        {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

netatmo:
  client_id: !secret netatmo_id
  client_secret: !secret netatmo_secret

home_connect:
  client_id: !secret homeconnect_client_id
  client_secret: !secret homeconnect_secret

http:
  base_url: !secret external_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - !secret raspi_ip
  cors_allowed_origins:
    - https://cast.home-assistant.io

websocket_api:

energy:

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://octopi.local/webcam/?action=snapshot
    mjpeg_url: http://octopi.local/webcam/?action=stream

backup:

input_number:

bluetooth: