homeassistant:
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
plant: !include plants.yaml
person: !include persons.yaml
light: !include lights.yaml

zone:
  - name: Home
    latitude: !secret lat
    longitude: !secret long
    radius: 50

mobile_app:

frontend:
  themes: !include themes.yaml

config:

lovelace:

api:

system_health:

auth:

updater:

discovery:

conversation:

sun:
  elevation: 350
  #device_sun_light_trigger:
  #  light_group: group.main_lights
  #  device_group: group.people
  #  disable_turn_off: 1

history:

recorder:
  db_url: !secret sql_db_url
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    entities:
      - sensor.time
      - sensor.internet_time
      - sensor.dark_sky_wind_gust # m/s
      - sensor.dark_sky_wind_speed # m/s
      - sensor.owm_wind_speed # m/s
      - sensor.dark_sky_pressure # mbar
      - sensor.owm_pressure # mbar

logbook:

map:

tts:
  - platform: google_translate
    service_name: google_say

device_tracker:
  - platform: nmap_tracker
    hosts: !secret ip_range
    exclude:
      - !secret raspi_ip
      - !secret nas_ip
    home_interval: 1
    new_device_defaults:
      track_new_devices: true

binary_sensor:
  - platform: workday
    country: AT
    province: 8
  - platform: uptimerobot
    api_key: !secret uptimerobot_api_key
  - platform: apcupsd

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
  - platform: zamg

apcupsd:

shopping_list:

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret chat_id_0

notify:
  - name: grubFX Notifier
    platform: telegram
    chat_id: !secret chat_id_0

pi_hole:
  host: !secret pihole_host
  api_key: !secret pihole_api_key

proximity:
  home:
    devices:
      - !secret tracker_0
    tolerance: 50

  cf:
    devices:
      - !secret tracker_0
    tolerance: 50

google_assistant:
  project_id: grubFX-home-assistant
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true

hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: true

media_player:
  - platform: androidtv
    host: !secret mibox_ip
    apps:
      tv.arte.plus7: "Arte"
      com.nousguide.android.orftvthek: "ORF TVthek"
      com.amazon.amazonvideo.livingroom: "Amazon Prime Video"
      com.nousguide.android.rbtv: "Red Bull TV"
      com.zdf.android.mediathek: "ZDFmediathek"
      com.zppntv: "ZAPPN TV"
      com.codingbuffalo.aerialdream: "Screensaver"
      de.prosiebensat1digital.sat1: "SAT.1"
    state_detection_rules:
      "com.netflix.ninja":
        - "media_session_state"
      "com.plexapp.android":
        - "paused":
            "media_session_state": 3 # this indentation is important!
            "wake_lock_size": 1 # this indentation is important!
        - "playing":
            "media_session_state": 3 # this indentation is important!
        - "standby"

wake_on_lan:

mqtt:
  discovery: true
  discovery_prefix: zwave2mqtt
  broker: !secret mqtt_broker
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

netatmo:
  client_id: !secret netatmo_id
  client_secret: !secret netatmo_secret
