- platform: group
  name: Couch Lights 
  entities:
    - light.color_temperature_light_1_2
    - light.color_temperature_light_2
    - light.color_temperature_light_3
    - light.color_temperature_light_4

- platform: group
  name: Office Lights
  entities:
    - light.hue_1
    - light.extended_color_light_1
