- platform: group
  name: Couch Lights 
  entities:
    - light.color_temperature_light_1_2
    - light.color_temperature_light_2
    - light.color_temperature_light_3
    - light.color_temperature_light_4
    - light.couch_muller_candle

- platform: group
  name: Office Lights
  entities:
    - light.hue_1
    - light.tradfri_candle
