resources:
  - type: js
    url: /local/monster-card.js?v=0.2.3
  - type: js
    url: /local/tracker-card.js?v=1.2.6
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: null
    url: /community_plugin/entity-attributes-card/entity-attributes-card.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: js
    url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: module
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: module
    url: /community_plugin/aftership-card/aftership-card.js
  - type: module
    url: /community_plugin/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
  - type: js
    url: /community_plugin/miflora-card/miflora-card.js
  - type: js
    url: /community_plugin/light-entity-card/light-entity-card.js
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: null
    url: /community_plugin/gauge-card/gauge-card.js
  - type: null
    url: /community_plugin/light-entity-row/light-entity-row.js
  - type: module
    url: /community_plugin/button-entity-row/button-entity-row.js
  - type: js
    url: /community_plugin/rgb-light-card/card.js
  - type: module
    url: /community_plugin/simple-thermostat/simple-thermostat.js
  - type: js
    url: /community_plugin/upcoming-media-card/upcoming-media-card.js
title: Home
views:
  - icon: mdi:home
    id: home
    path: home
    theme: Backend-selected
    title: Home
    badges: []
    cards:
      - show_header_toggle: false
        title: Date & Time
        state_color: false
        type: entities
        entities:
          - entity: sensor.date_time_iso
            format: date
          - entity: sensor.internet_time
          - entity: binary_sensor.workday_sensor
      - card:
          show_state: true
          title: People
          type: glance
        filter:
          include:
            - domain: person
        id: people
        type: custom:auto-entities
      - card:
          show_state: false
          title: Active Devices
          type: glance
        filter:
          exclude:
            - domain: group
            - domain: person
            - state: not_home
            - state: unavailable
          include:
            - state: home
            - domain: device_tracker
        unique: true
        type: custom:auto-entities
      - dark_mode: false
        entities:
          - entity: zone.home
          - entity: person.felix
          - entity: person.anna
        hours_to_show: 0
        type: map
      - cards:
          - entities:
              - entity: binary_sensor.roobert_bin_full
                name: Bin full?
            type: entities
          - color_thresholds:
              - color: green
                value: 100
              - color: orange
                value: 50
              - color: red
                value: 0
            entities:
              - entity: sensor.roobert_battery
            hours_to_show: 72
            lower_bound: 0
            show:
              state: false
              icon: false
              labels: true
              points: false
            type: custom:mini-graph-card
            upper_bound: 100
          - type: custom:vacuum-card
            entity: vacuum.roobert
        title: Roobert
        type: custom:vertical-stack-in-card
  - icon: mdi:silverware
    id: lights
    path: diningroom
    title: Dining Room
    badges: []
    cards:
      - type: light
        entity: light.ikea_tradfri_bulb
        name: Table Light
      - type: media-control
        entity: media_player.table
  - title: Living Room
    icon: mdi:sofa
    path: livingroom
    badges: []
    cards:
      - type: media-control
        entity: media_player.dht_s416_5595
      - cards:
          - entities:
              - entity: light.couch_muller_candle
                name: Shelf Light
                min: 1
                toggle: true
                type: custom:slider-entity-row
            type: entities
          - entity: light.couch_lights
            type: light
        title: Livingroom Lights
        type: custom:vertical-stack-in-card
      - cards:
          - color_thresholds:
              - color: blue
                value: 15
              - color: green
                value: 22
              - color: orange
                value: 30
              - color: red
                value: 35
            entities:
              - entity: sensor.netatmo_netatmo_temperature
            height: 100
            hours_to_show: 72
            lower_bound: ~20
            refresh_interval: 10
            show:
              average: true
              extrema: true
              labels: true
            type: custom:mini-graph-card
            upper_bound: ~30
          - color_thresholds:
              - color: blue
                value: 80
              - color: green
                value: 50
              - color: green
                value: 40
              - color: gray
                value: 20
            entities:
              - entity: sensor.netatmo_netatmo_humidity
            height: 100
            hours_to_show: 72
            lower_bound: ~0
            refresh_interval: 10
            show:
              average: true
              extrema: true
              labels: true
            type: custom:mini-graph-card
            upper_bound: ~100
          - cards:
              - entity: sensor.netatmo_netatmo_co2
                max: 2000
                severity:
                  green: 0
                  red: 1000
                  yellow: 500
                title: CO2
                type: gauge
              - entity: sensor.netatmo_netatmo_noise
                severity:
                  green: 0
                  red: 50
                  yellow: 40
                title: CO2
                type: gauge
            type: horizontal-stack
          - entities:
              - entity: sensor.netatmo_netatmo_pressure
              - entity: sensor.netatmo_netatmo_wifi
            show_header_toggle: false
            type: entities
            title: Luftstange
        type: custom:vertical-stack-in-card
  - icon: mdi:desk
    path: office
    title: Office
    badges: []
    cards:
      - cards:
          - entities:
              - entity: light.hue_1
                min: 1
                toggle: true
                name: Office Main
                type: custom:slider-entity-row
              - entity: light.tradfri_candle
                min: 1
                toggle: true
                type: custom:slider-entity-row
            type: entities
          - entity: light.office_lights
            name: Office
            type: light
        title: Office
        type: custom:vertical-stack-in-card
      - type: entities
        entities:
          - sensor.plex_nas
  - icon: mdi:flower
    path: balcony
    title: Balcony
    badges: []
    cards:
      - cards:
          - color_thresholds:
              - color: blue
                value: 10
              - color: green
                value: 20
              - color: orange
                value: 30
              - color: red
                value: 40
            entities:
              - entity: sensor.netatmo_netatmo_balkon_temperature
            height: 200
            hours_to_show: 72
            lower_bound: ~10
            refresh_interval: 10
            show:
              average: true
              extrema: true
              labels: true
            type: custom:mini-graph-card
            upper_bound: ~40
          - color_thresholds:
              - color: blue
                value: 90
              - color: green
                value: 60
              - color: green
                value: 40
              - color: gray
                value: 20
            entities:
              - entity: sensor.netatmo_netatmo_balkon_humidity
            height: 200
            hours_to_show: 72
            lower_bound: ~0
            refresh_interval: 10
            show:
              average: true
              extrema: true
              labels: true
            type: custom:mini-graph-card
            upper_bound: ~100
          - entities:
              - entity: sensor.netatmo_netatmo_balkon_battery_percent
              - entity: sensor.netatmo_netatmo_balkon_radio
            show_header_toggle: false
            type: entities
        title: Balkon
        type: custom:vertical-stack-in-card
  - title: ''
    icon: mdi:movie
    path: media
    badges: []
    cards:
      - type: media-control
        entity: media_player.all_speakers
      - cards:
          - entity: scene.dim_all
            icon: mdi:brightness-6
            name: Dimmed
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.dim_all
            type: entity-button
          - entity: scene.futter
            icon: mdi:silverware-variant
            name: Futter
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.futter
            type: entity-button
          - entity: scene.movie_time
            icon: mdi:movie
            name: Movie
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.movie_time
            type: entity-button
        layout: horizontal
        type: custom:layout-card
      - type: custom:upcoming-media-card
        entity: sensor.radarr_upcoming_media
        title: Upcoming Movies
      - type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
        title: Upcoming TV
  - icon: mdi:weather-partly-cloudy
    id: weather
    path: weather
    title: Weather
    badges: []
    cards:
      - type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=48.2&lon=16.4&zoom=15&level=surface&overlay=temp&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=48.2&detailLon=16.4&metricWind=default&metricTemp=default&radarRange=-1
      - entity: weather.zamg_unknown_station
        name: ZAMG
        type: custom:weather-card
        number_of_forecasts: '7'
        hourly_forecast: true
        forecast: true
      - entities:
          - entity: sensor.mean_wind_speed
        hours_to_show: 72
        icon: mdi:weather-windy
        lower_bound: 0
        name: Wind (ZAMG)
        refresh_interval: 10
        type: custom:mini-graph-card
      - color_thresholds:
          - color: red
            value: 40
          - color: orange
            value: 30
          - color: green
            value: 20
          - color: blue
            value: 10
        entities:
          - entity: sensor.mean_temperature
        height: 200
        hours_to_show: 72
        icon: mdi:thermometer
        lower_bound: ~10
        name: Mean Temeprature (Netatmo, ZAMG)
        refresh_interval: 10
        show:
          extrema: true
          labels: true
          average: true
        type: custom:mini-graph-card
        upper_bound: ~40
      - entities:
          - entity: sensor.mean_humidity
        hours_to_show: 72
        icon: mdi:water-percent
        lower_bound: ~0
        name: Mean Humidity (Netatmo, ZAMG)
        refresh_interval: 10
        type: custom:mini-graph-card
        upper_bound: ~100
        color_thresholds:
          - color: blue
            value: 90
          - color: green
            value: 60
          - color: green
            value: 40
          - color: gray
            value: 20
      - entities:
          - entity: sensor.mean_pressure
        hours_to_show: 72
        icon: mdi:gauge
        name: Pressure (ZAMG)
        refresh_interval: 10
        show:
          extrema: true
          labels: true
          average: true
        title: Pressure
        type: custom:mini-graph-card
      - entities:
          - entity: sensor.graz_precipitation
            name: Precipitation
          - entity: sensor.dark_sky_precip_intensity
            name: Intensity
            y_axis: secondary
        height: 200
        hours_to_show: 72
        refresh_interval: 10
        show:
          labels: true
          labels_secondary: true
        type: custom:mini-graph-card
      - entities:
          - entity: sensor.mean_dewpoint
        hours_to_show: 72
        icon: mdi:coolant-temperature
        name: Dew Point (ZAMG)
        refresh_interval: 10
        show:
          extrema: true
          labels: true
          average: true
        type: custom:mini-graph-card
  - icon: mdi:chip
    id: system
    path: system
    title: System
    badges: []
    cards:
      - cards:
          - card:
              show_header_toggle: false
              title: UPS
              type: entities
            filter:
              exclude:
                - entity_id: sensor.ups_battery
                - entity_id: sensor.ups_load
              include:
                - entity_id: '*sensor.ups*'
            type: custom:auto-entities
          - cards:
              - entity: sensor.ups_battery
                severity:
                  green: 75
                  red: 0
                  yellow: 50
                title: UPS Battery
                type: gauge
              - entity: sensor.ups_load
                severity:
                  green: 0
                  red: 75
                  yellow: 50
                title: UPS Load
                type: gauge
            type: horizontal-stack
        id: ups
        type: custom:vertical-stack-in-card
      - entities:
          - binary_sensor.nas
          - binary_sensor.vserv
          - binary_sensor.raspi
        id: uptime
        show_header_toggle: false
        title: UptimeRobot
        type: entities
      - card:
          show_header_toggle: false
          title: PiHole
          type: entities
        filter:
          include:
            - entity_id: '*pi_hole*'
            - entity_id: '*pihole*'
        id: pihole
        type: custom:auto-entities
      - cards:
          - cards:
              - entity: sensor.processor_use_percent
                name: CPU Usage
                severity:
                  green: 0
                  red: 80
                  yellow: 50
                type: gauge
              - entity: sensor.memory_use_percent
                name: Memory Usage
                severity:
                  green: 0
                  red: 80
                  yellow: 50
                type: gauge
            type: horizontal-stack
          - color_thresholds:
              - color: blue
                value: 20
              - color: green
                value: 30
              - color: orange
                value: 40
              - color: red
                value: 60
            entities:
              - entity: sensor.temperature_zone0
                name: CPU Temperature
            height: 200
            hours_to_show: 24
            lower_bound: ~20
            points_per_hour: 6
            refresh_interval: 1
            show:
              labels: true
            type: custom:mini-graph-card
            upper_bound: ~50
          - cards:
              - entity: sensor.load_1m
                max: 3
                min: 0
                name: load 1
                severity:
                  green: 0
                  red: 2
                  yellow: 1
                type: gauge
              - entity: sensor.load_5m
                max: 3
                min: 0
                name: load 5
                severity:
                  green: 0
                  red: 2
                  yellow: 1
                type: gauge
              - entity: sensor.load_15m
                max: 3
                min: 0
                name: load 15
                severity:
                  green: 0
                  red: 2
                  yellow: 1
                type: gauge
            title: System Load
            type: horizontal-stack
          - entities:
              - entity: sensor.load_1m
                name: Load1
              - entity: sensor.load_5m
                name: Load5
              - entity: sensor.load_15m
                name: Load15
            height: 200
            hours_to_show: 24
            line_width: 2
            lower_bound: 0
            name: Load
            points_per_hour: 12
            show:
              extrema: true
              fill: false
              labels: true
              points: false
              state: false
            type: custom:mini-graph-card
            update_interval: 1
            upper_bound: ~1
        id: stats
        title: System Stats
        type: custom:vertical-stack-in-card
      - type: sensor
        entity: sensor.test_humidity
        graph: line
      - type: sensor
        entity: sensor.test_temperature
        graph: line
        detail: 1
