- platform: zamg
  name: ZAMG
  monitored_conditions:
    - pressure
    - humidity
    - wind_speed
    - temperature
    - precipitation
    - dewpoint

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - temperature_high
    - temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase

- platform: template
  sensors:
    owm_wind_speed_kmh:
      unit_of_measurement: 'km/h'
      value_template: "{{ states('sensor.owm_wind_speed')| float * 3.6 | round(1) }}"
    owm_pressure_hpa:
      unit_of_measurement: 'hPa'
      value_template: "{{ states('sensor.owm_pressure') }}"
    dark_sky_wind_speed_kmh:
      unit_of_measurement: 'km/h'
      value_template: "{{ states('sensor.dark_sky_wind_speed')| float * 3.6 | round(1) }}"
    dark_sky_pressure_hpa:
      unit_of_measurement: 'hPa'
      value_template: "{{ states('sensor.dark_sky_pressure') }}"
    oomi_multisensor_lx:
      unit_of_measurement: 'lx'
      value_template: "{{ states('sensor.oomi_multisensor_illuminance') }}"

- platform: min_max
  type: mean
  name: mean_dewpoint
  entity_ids:
    - sensor.zamg_dewpoint
  round_digits: 1

- platform: min_max
  type: mean
  name: mean_wind_speed
  entity_ids:
    - sensor.zamg_wind_speed
  round_digits: 1

- platform: min_max
  type: mean
  name: mean_temperature
  entity_ids:
    - sensor.netatmo_balkon_temperature
    - sensor.zamg_temperature
  round_digits: 1

- platform: min_max
  type: mean
  name: mean_humidity
  entity_ids:
    - sensor.netatmo_balkon_humidity
    - sensor.zamg_humidity
  round_digits: 0

- platform: min_max
  type: mean
  name: mean_pressure
  entity_ids:
    - sensor.zamg_pressure
  round_digits: 0